name: py东东超市兑换

on:
    workflow_dispatch:
    schedule:
        - cron: "56 15* * *"
    watch:
        types: [started]
    repository_dispatch:
        types: jd_blueCoin.py

jobs:
    build:
        runs-on: ubuntu-latest
        if: github.event.repository.owner.id == github.event.sender.id
        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: "Set up Python"
              uses: actions/setup-python@v1
              with:
                  python-version: 3.7

            - name: "安装依赖包"
              run: pip install -r ./requirements.txt

            - name: "运行 喜马拉雅极速版"
              run: python3 xmly_speed.py
              env:
                  A: ${{ github.event.client_payload.A || secrets.A }}
                  B: ${{ github.event.client_payload.B || secrets.B }}
                  C: ${{ github.event.client_payload.C || secrets.C }}
                  D: ${{ github.event.client_payload.D || secrets.D }}
                  E: ${{ github.event.client_payload.E || secrets.E }}
                  F: ${{ github.event.client_payload.F || secrets.F }}
                  G: ${{ github.event.client_payload.G || secrets.G }}
                  H: ${{ github.event.client_payload.H || secrets.H }}
                  I: ${{ github.event.client_payload.I || secrets.I }}
                  J: ${{ github.event.client_payload.J || secrets.J }}
                  K: ${{ github.event.client_payload.K || secrets.K }}
                  L: ${{ github.event.client_payload.L || secrets.L }}
                  M: ${{ github.event.client_payload.M || secrets.M }}
                  N: ${{ github.event.client_payload.N || secrets.N }}
                  O: ${{ github.event.client_payload.O || secrets.O }}
                  P: ${{ github.event.client_payload.P || secrets.P }}
                  Q: ${{ github.event.client_payload.Q || secrets.Q }}
                  R: ${{ github.event.client_payload.R || secrets.R }}
                  S: ${{ github.event.client_payload.S || secrets.S }}
                  T: ${{ github.event.client_payload.T || secrets.T }}
                  U: ${{ github.event.client_payload.U || secrets.U }}
                  V: ${{ github.event.client_payload.V || secrets.V }}
                  W: ${{ github.event.client_payload.W || secrets.W }}
                  X: ${{ github.event.client_payload.X || secrets.X }}
                  Y: ${{ github.event.client_payload.Y || secrets.Y }}
                  Z: ${{ github.event.client_payload.Z || secrets.Z }}
                  XMLY_SPEED_COOKIE: ${{ github.event.client_payload.XMLY_SPEED_COOKIE || secrets.XMLY_SPEED_COOKIE }}
                  XMLY_ACCUMULATE_TIME: ${{ github.event.client_payload.XMLY_ACCUMULATE_TIME || secrets.XMLY_ACCUMULATE_TIME }}
                  XMLY_ACCUMULATE_INDEX: ${{ github.event.client_payload.XMLY_ACCUMULATE_INDEX || secrets.XMLY_ACCUMULATE_INDEX }}
                  XMLY_ACCUMULATE_HOURS: ${{ github.event.client_payload.XMLY_ACCUMULATE_HOURS || secrets.XMLY_ACCUMULATE_HOURS }}
                  XMLY_ANDROID_AGENT: ${{ github.event.client_payload.XMLY_ANDROID_AGENT || secrets.XMLY_ANDROID_AGENT }}
                  PUSH_KEY: ${{ github.event.client_payload.PUSH_KEY || secrets.PUSH_KEY }}
                  BARK_PUSH: ${{ github.event.client_payload.BARK_PUSH || secrets.BARK_PUSH }}
                  BARK_SOUND: ${{ github.event.client_payload.BARK_SOUND || secrets.BARK_SOUND }}
                  TG_BOT_TOKEN: ${{ github.event.client_payload.TG_BOT_TOKEN || secrets.TG_BOT_TOKEN }}
                  TG_USER_ID: ${{ github.event.client_payload.TG_USER_ID || secrets.TG_USER_ID }}
                  SYNCURL: https://raw.githubusercontent.com/curtinlv/JD-Script/main/jd_blueCoin.py
